# Generated by Django 5.1.1 on 2024-09-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.CharField(choices=[('chemical', 'chemical'), ('mechanical', 'mechanical'), ('scientist', 'scientist')], max_length=50)),
                ('salary', models.BigIntegerField()),
            ],
        ),
    ]
