# Generated by Django 5.1.1 on 2024-09-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('subject', models.CharField(choices=[('maths', 'Maths'), ('english', 'English'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('bio', 'Biology')], max_length=40)),
                ('gender', models.CharField(choices=[('boy', 'boy'), ('girl', 'girl'), ('other', 'other')], max_length=50)),
            ],
        ),
    ]
