# Generated by Django 5.1.1 on 2024-09-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('salary', models.BigIntegerField()),
                ('domain', models.CharField(choices=[('SW', 'software developer'), ('FD', 'FrontDeveloper'), ('FullStack', 'FullStack Developer'), ('DS', 'Data Scientist')], max_length=50)),
            ],
        ),
    ]
