# Generated by Django 5.1.1 on 2024-09-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='passby',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
