# Generated by Django 5.0.6 on 2024-09-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filterapp', '0002_employee_passby'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.BigIntegerField()),
            ],
        ),
    ]
